import type { NormalizedAsset } from "@/lib/domain/types";
import { classifyLicense } from "@/lib/media/rights";
import { BaseProvider } from "./base";
import { fetchJson, stripHtml } from "./http";
import { assetId, type ConnectionStatus, type ProviderCredentials, type SearchParams, type SearchResult } from "./types";

// Public MediaWiki Action API — no key needed for read/search.
// An optional OAuth 2 bearer token (WIKIMEDIA_ACCESS_TOKEN) raises rate limits; the
// request shape is unchanged, so authentication is a header, not an architecture change.
const API = "https://commons.wikimedia.org/w/api.php";

const META_FIELDS = [
  "LicenseShortName", "LicenseUrl", "Artist", "Credit", "ImageDescription", "DateTimeOriginal",
  "Categories", "AttributionRequired", "NonFree", "Restrictions", "UsageTerms", "ObjectName",
].join("|");

const AI_EXCLUSIONS = [
  '-hastemplate:"PD-algorithm"',
  '-incategory:"AI-generated images"',
  '-incategory:"Images generated by Stable Diffusion"',
].join(" "); // More negations make CirrusSearch silently return nothing on larger pages; other AI categories are caught by looksAiGenerated() on each result.

interface ExtValue {
  value?: string;
}
interface Derivative {
  src: string;
  type: string;
  width: number;
  height: number;
}
interface ImageInfo {
  url: string;
  derivatives?: Derivative[];
  descriptionurl: string;
  thumburl?: string;
  width?: number;
  height?: number;
  duration?: number;
  mime?: string;
  timestamp?: string;
  extmetadata?: Record<string, ExtValue>;
}
interface Page {
  pageid: number;
  title: string;
  index?: number;
  imageinfo?: ImageInfo[];
  videoinfo?: ImageInfo[];
}
interface QueryResponse {
  continue?: { gsroffset?: number };
  query?: { pages?: Page[] };
}

function cleanTitle(title: string) {
  return title.replace(/^File:/, "").replace(/\.[a-z0-9]+$/i, "").replace(/_/g, " ");
}

function yearOf(s: string | null): number | null {
  const m = s?.match(/\b(1[5-9]\d\d|20\d\d)\b/);
  return m ? Number(m[1]) : null;
}

export class WikimediaProvider extends BaseProvider {
  readonly id = "wikimedia" as const;
  readonly name = "Wikimedia Commons";
  readonly requiresKey = false;

  supportsImages() {
    return true;
  }
  supportsVideo() {
    return true;
  }
  isConfigured() {
    return true;
  }

  private headers(creds: ProviderCredentials): Record<string, string> {
    return creds.wikimediaToken ? { Authorization: `Bearer ${creds.wikimediaToken}` } : {};
  }

  toAsset(p: Page): NormalizedAsset | null {
    const info = p.videoinfo?.[0] ?? p.imageinfo?.[0];
    if (!info?.url) return null;
    const m = info.extmetadata ?? {};
    const v = (k: string) => stripHtml(m[k]?.value) ?? null;

    const license = v("LicenseShortName") ?? v("UsageTerms") ?? "Unknown";
    const licenseUrl = m.LicenseUrl?.value ?? null;
    const rights = classifyLicense(license, licenseUrl);
    const notes = [...rights.notes];
    if (m.NonFree?.value === "true") {
      rights.status = "RESTRICTED";
      notes.push("Marked non-free on Commons.");
    }
    const restrictions = v("Restrictions");
    if (restrictions) {
      notes.push(`Additional restrictions: ${restrictions} (e.g. trademark or personality rights).`);
      if (rights.status === "CLEAR" || rights.status === "ATTRIBUTION_REQUIRED") rights.status = "USER_REVIEW";
    }
    const attributionRequired = m.AttributionRequired?.value === "true" || rights.attributionRequired;
    const author = v("Artist") ?? v("Credit");
    const title = v("ObjectName") ?? cleanTitle(p.title);
    const isVideo = (info.mime ?? "").startsWith("video/");
    // Wikimedia only serves standard thumbnail widths; use the 1920px rendition for stills and
    // a ≤1080p transcode for video instead of multi-megabyte originals (kinder to upload servers).
    const still1920 = info.thumburl && /\/1920px-/.test(info.thumburl) ? info.thumburl : info.url;
    const small = info.thumburl ? info.thumburl.replace(/\/(\d+)px-/, "/500px-") : null;
    const transcode = (info.derivatives ?? [])
      .filter((d) => /\/transcoded\//.test(d.src) && d.height <= 1080 && d.height >= 480)
      .sort((a, b) => b.height - a.height)[0];
    const renderUrl = isVideo ? (transcode?.src ?? info.url) : still1920;
    const date = v("DateTimeOriginal");
    const year = yearOf(date);

    return {
      id: assetId("wikimedia", p.pageid),
      provider: "wikimedia",
      providerAssetId: String(p.pageid),
      type: isVideo ? "video" : "photo",
      title,
      description: v("ImageDescription"),
      thumbnailUrl: small ?? info.thumburl ?? null,
      mediaUrl: renderUrl,
      previewUrl: info.thumburl ?? null,
      downloadUrl: info.url,
      width: info.width ?? null,
      height: info.height ?? null,
      duration: isVideo ? (info.duration ?? null) : null,
      author,
      authorUrl: null,
      sourceUrl: info.descriptionurl,
      license,
      licenseUrl,
      attribution: `${title} — ${author ?? "Unknown author"}, ${license}, via Wikimedia Commons`,
      attributionRequired,
      rightsStatus: rights.status,
      rightsNotes: notes,
      retrievedAt: new Date().toISOString(),
      date,
      categories: (m.Categories?.value ?? "").split("|").filter(Boolean),
      archival: year !== null && year < 2000,
      score: 0,
    };
  }

  private async search(params: SearchParams, filetype: "bitmap" | "video", creds: ProviderCredentials) {
    const perPage = params.perPage ?? 15;
    const page = params.page ?? 1;
    const q = new URLSearchParams({
      action: "query",
      format: "json",
      formatversion: "2",
      generator: "search",
      // Exclude AI-generated media at the source: Commons licenses AI output with {{PD-algorithm}}
      // and files it under AI categories. Metadata is re-checked by the orchestrator too.
      gsrsearch: `${params.query} filetype:${filetype} ${AI_EXCLUSIONS}`,
      gsrnamespace: "6",
      gsrlimit: String(Math.min(perPage, 50)),
      gsroffset: String((page - 1) * perPage),
      prop: "videoinfo",
      viprop: "url|size|mime|extmetadata|timestamp|derivatives",
      viurlwidth: "1920",
      viextmetadatafilter: META_FIELDS,
    });
    const data = await fetchJson<QueryResponse>(this.id, `${API}?${q}`, { headers: this.headers(creds) });
    const pages = [...(data.query?.pages ?? [])].sort((a, b) => (a.index ?? 0) - (b.index ?? 0));
    let assets = pages.map((p) => this.toAsset(p)).filter((a): a is NormalizedAsset => a !== null);
    if (params.minWidth) assets = assets.filter((a) => (a.width ?? 0) >= params.minWidth!);
    if (params.minDuration) assets = assets.filter((a) => a.type !== "video" || (a.duration ?? 0) >= params.minDuration!);
    return { assets, page, hasMore: data.continue?.gsroffset !== undefined };
  }

  searchImages(params: SearchParams, creds: ProviderCredentials): Promise<SearchResult> {
    return this.search(params, "bitmap", creds);
  }

  searchVideos(params: SearchParams, creds: ProviderCredentials): Promise<SearchResult> {
    return this.search(params, "video", creds);
  }

  async getAsset(providerAssetId: string, creds: ProviderCredentials) {
    if (!/^\d+$/.test(providerAssetId)) return null;
    const q = new URLSearchParams({
      action: "query",
      format: "json",
      formatversion: "2",
      pageids: providerAssetId,
      prop: "videoinfo",
      viprop: "url|size|mime|extmetadata|timestamp|derivatives",
      viurlwidth: "1920",
      viextmetadatafilter: META_FIELDS,
    });
    const data = await fetchJson<QueryResponse>(this.id, `${API}?${q}`, { headers: this.headers(creds) });
    const page = data.query?.pages?.[0];
    return page ? this.toAsset(page) : null;
  }

  async test(creds: ProviderCredentials): Promise<ConnectionStatus> {
    const status = await super.test(creds);
    if (status.state === "public" && creds.wikimediaToken) return { ...status, state: "connected" };
    return status;
  }
}
