import { existsSync } from "node:fs";
import path from "node:path";
import type { PaperStyle, SfxKind } from "@/lib/domain/types";

/**
 * Local royalty-safe library generated by `npm run assets:generate`: procedurally synthesised
 * SFX and music (FFmpeg), paper textures, annotation overlays, OFL fonts and the demo narration.
 */
export const LIBRARY_DIR = process.env.ASSET_LIBRARY_DIR || path.join(process.cwd(), "assets", "library");

export const library = {
  dir: LIBRARY_DIR,
  sfx: (kind: SfxKind) => path.join(LIBRARY_DIR, "sfx", `${kind}.wav`),
  texture: (style: PaperStyle) => path.join(LIBRARY_DIR, "textures", `${style}.jpg`),
  overlay: (name: "circle" | "arrow" | "cursor") => path.join(LIBRARY_DIR, "overlays", `${name}.png`),
  fontsDir: path.join(LIBRARY_DIR, "fonts"),
  music: (name: string) => path.join(LIBRARY_DIR, "music", `${name}.m4a`),
  demoNarration: path.join(LIBRARY_DIR, "demo", "narration.wav"),
  demoScript: path.join(LIBRARY_DIR, "demo", "script.txt"),
};

export { MUSIC_TRACKS } from "./libraryTracks";

export function libraryReady(): boolean {
  return existsSync(library.texture("white_paper")) && existsSync(library.sfx("whoosh"));
}

export function fontAvailable(file: string): boolean {
  return existsSync(path.join(library.fontsDir, file));
}
