import { existsSync } from "node:fs";
import { library, MUSIC_TRACKS } from "@/lib/render/library";

/**
 * Music provider abstraction. V1 ships two sources — the generated royalty-safe library and
 * the user's own upload. A licensed music API can be added later by implementing this
 * interface; copyrighted music is never selected automatically.
 */
export interface MusicTrack {
  key: string;
  name: string;
  description: string;
  licence: string;
}

export interface MusicProvider {
  readonly id: string;
  list(): Promise<MusicTrack[]>;
  /** Local file path for rendering, or null if unavailable. */
  resolve(key: string): Promise<string | null>;
}

export class LocalLibraryMusicProvider implements MusicProvider {
  readonly id = "library";
  async list() {
    return MUSIC_TRACKS.map((t) => ({ ...t, licence: "Generated by DocuCut (no third-party rights)" }));
  }
  async resolve(key: string) {
    const p = library.music(key);
    return MUSIC_TRACKS.some((t) => t.key === key) && existsSync(p) ? p : null;
  }
}

export const musicProviders: MusicProvider[] = [new LocalLibraryMusicProvider()];
